
# 3.2.3 Уход от циклов: обработка данных с применением массивов

## Задание 1

**Условие:**
Создайте ```3``` случайных целочисленных массива ```ndarray``` размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте из данных массивов один трехмерный массив. Вычтите поэлементно первую матрицу из полученного трехмерного массива методом укладывания. Найдите наибольший элемент в полученном массиве. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```4```)



**Решение:**

In [ ]:
import numpy as np

np.random.seed(1000)


arr1 = np.random.randint(0, 11, size=(10, 10))
arr2 = np.random.randint(0, 11, size=(10, 10))
arr3 = np.random.randint(0, 11, size=(10, 10))

three_dim_array = np.array([arr1, arr2, arr3])

result_array = three_dim_array - three_dim_array[0]

max_element = np.max(result_array)

print("Наибольший элемент в полученном массиве:", max_element)


Наибольший элемент в полученном массиве: 10


## Задание 2

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. С помощью методов ```np.mean()``` и ```np.std()``` центрируйте и нормируйте элементы в столбцах. Найдите разброс полученных значений в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Кортеж чисел (например, ```(-0.45,0.89)```)



**Решение:**

In [ ]:
import numpy as np

np.random.seed(1000)

arr = np.random.randint(0, 11, size=(10, 10))

centered_arr = arr - np.mean(arr, axis=0)

normalized_arr = centered_arr / np.std(centered_arr, axis=0)

spread = np.ptp(normalized_arr)

print("Случайный массив:")
print(arr)
print("\nЦентрированный и нормированный массив:")
print(normalized_arr)
print("\nРазброс значений в полученной матрице:", spread)


Случайный массив:
[[ 3  7  7  0  1  0  9  8  9  4]
 [10 10  9  4  4  2  9  8  2  4]
 [ 2  5 10  5  4  0  4  2  5 10]
 [ 4  7  0  4  7  1  0  2  1  7]
 [ 1  5  6  5  7  8  8  2  2  9]
 [ 6 10 10  3  3  6  5  8  4  1]
 [ 0  9  1  8  8  0  2  9  3 10]
 [ 9  6  2  9  5  8  5  6  9  6]
 [ 7  6  3  4  8  1  3  7  2  0]
 [ 4  4  1  6  5  1  4  1  7  4]]

Центрированный и нормированный массив:
[[-0.50495552  0.04944682  0.55945325 -2.         -1.92506684 -0.86204366
   1.44148324  0.89950042  1.62229492 -0.4472136 ]
 [ 1.70422489  1.53285135  1.09226586 -0.33333333 -0.5500191  -0.2234928
   1.44148324  0.89950042 -0.84641474 -0.4472136 ]
 [-0.82055272 -0.93948954  1.35867217  0.08333333 -0.5500191  -0.86204366
  -0.31642315 -1.0993894   0.21160368  1.34164079]
 [-0.18935832  0.04944682 -1.30539091 -0.33333333  0.82502865 -0.54276823
  -1.72274826 -1.0993894  -1.19908755  0.4472136 ]
 [-1.13614993 -0.93948954  0.29304694  0.08333333  0.82502865  1.69215977
   1.08990196 -1.0993894  -0.84641474 