
# 3.2.4 Математические и статистические операции

## Задание 1

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` размера ```(15,15)``` элементов, принадлежащих отрезку ```[1,10]```. С помощью методов булевых массивов найдите количество элементов в полученном массиве, которые являются полными квадратами. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```4```)


**Решение:**

In [ ]:
import numpy as np

np.random.seed(1000)
array = np.random.randint(1, 11, (15, 15))


is_square = np.sqrt(array) % 1 == 0

count_squares = np.sum(is_square)

print("Сгенерированный массив:")
print(array)
print("\nКоличество элементов, являющихся полными квадратами:", count_squares)


Сгенерированный массив:
[[ 4  8  8  1  2  1 10  9 10  5 10  5  5  3 10]
 [ 9  3  5  3  6  6  5  1  5  3  6  5  8  1  5]
 [ 8  2  1  3  2  8  2  6  7  6  8  9  9  3  3]
 [10  7  4  4  7  6  9  5  2  1 10  2  9  9  1]
 [ 3 10  4 10  7  3 10  6  9  6  7 10  7  8  7]
 [ 4  5  9  2  4  8  3  1  5  5  2  7  6  2  5]
 [ 2  8  5  6  1  7  3 10  8  1  9  1  6  4  1]
 [ 5  4  4  4  7  5  8  3  5  5  3  5  2  3  4]
 [10  1  6  3  2  1  7  9 10  7  2  2  1  9  5]
 [ 3  3  2  9  3  1  2  2  2  4  7  5  7  9  2]
 [10  4  6  1  2  2  7 10  6  2  2  9  8  4  4]
 [10  1  3  1  3  9  6  4  3  6  4  8  4  5 10]
 [ 5  1  7  5  8  6  1  8 10  6  7  4 10  9  8]
 [ 1  3  4  4  8  2  7  4  5  3  9  4  1  1  2]
 [ 4  5  6  8 10  5  3  2  5  3  4  9  4  4  8]]

Количество элементов, являющихся полными квадратами: 70


## Задание 2

**Условие:**
Напишите функцию, которая принимает на вход квадратную матрицу, возводит ее в степень ```100``` и находит ее определитель. Если определитель отличен от нуля, то функция возвращает определитель матрицы, которая является обратной к транспанированной исходной матрице, иначе - ноль. Проверьте работоспособность на матрице, указанной в пункте решение.

**Формат ответа:**
Число (например, ```2.7```)



**Решение:**

In [ ]:
_INPUT_MATR_ = np.array([[2,5,7],
                        [6,3,4],
                        [5,-2,-3]])

In [ ]:
import numpy as np

def process_matrix(matrix):
    power_100 = np.linalg.matrix_power(matrix, 100)
    det = np.linalg.det(power_100)

    if det != 0:
        inverse_transpose = np.linalg.inv(matrix.T)
        return np.linalg.det(inverse_transpose)
    else:
        return 0

# Входная матрица
input_matrix = np.array([[2, 5, 7],
                          [6, 3, 4],
                          [5, -2, -3]])

result = process_matrix(input_matrix)
print("Результат:", result)


Результат: -0.9999999999999121


## Задание 3

**Условие:**
Создайте два случайных массива длины ```100```, первый из которых является выборкой из нормального распределения, а второй - равномерного распределения на полуинтервале ```[0,1)```. Найдите абсолютные значения разности средних и среднеквадратических отклонений у полученных массивов.

**Формат ответа:**
Кортеж чисел (например, ```(2.7, 0.0)```)




**Решение:**

In [ ]:
import numpy as np


normal_array = np.random.normal(loc=0, scale=1, size=100)

uniform_array = np.random.uniform(low=0, high=1, size=100)

mean_normal = np.mean(normal_array)
std_normal = np.std(normal_array)

mean_uniform = np.mean(uniform_array)
std_uniform = np.std(uniform_array)

diff_mean = np.abs(mean_normal - mean_uniform)
diff_std = np.abs(std_normal - std_uniform)

print("Абсолютная разность средних:", diff_mean)
print("Абсолютная разность среднеквадратических отклонений:", diff_std)


Абсолютная разность средних: 0.46587997523261443
Абсолютная разность среднеквадратических отклонений: 0.686335223874882
